accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('signup', views.signup_view, name='signup'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
]

articles/urls.py
from django.urls import path
from . import views

# We create app name to prevent making misstake in case of having 2 same name in two urls files
app_name = 'articles'
urlpatterns = [
# '' or '/' is root page (home) and here our home page is (www.mosihere/articles)
    path('', views.articles_list, name='list'),
    path('create', views.create_article, name='create'),
    path('<slug>', views.article_detail, name='detail'),
    # Here when sth type after home( here home is articles/ ) will know as slug and will add after articles/
]

djangoBlog/urls.py
from django.contrib import admin
from django.urls import path, include
# when we create a new app,we have to create a urls.py file for that
# also we have to use include funtion to say to mail urls.py(means here)
# look at that urls.py like urls :) we have to import include module :)



# we import views here
from . import views
# We import bellow modile for static files such as html-css-js
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# Here we import setting.py
from django.conf import settings


# With this we can access URL
from django.conf.urls.static import static


from articles.views import articles_list
# here we must use "path" and pass two parameters to that :)
# first parameter is our url for example www.mosihere.com/about
# second parameter is our Function that we Define in  File "Views.py"
# Tip --> '/' is our root ( Home ) and also we can use ' ' and if we connect
# to http:127.0.0.1:8000 we will see this page :)
urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', views.about),
    # for import a url from another app urls.py we have to use path like example bellow:
    path('articles/', include('articles.urls')),
    # it means if user wanna check articles page, include articles.urls
    # Tip --> (it means urls.py file of articles App)

    path('accounts/', include('accounts.urls')),
    path('', articles_list),

]

# Some urls will add to our main urls :)
urlpatterns += staticfiles_urlpatterns()

# This will add this url to the folder that our medias keeping there
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

# Tip --> Slug is something like details of a urls
# for example mosihere/articles/what-is-linux
# for a long text we should use TextField()
class Articles(models.Model):
    title = models.CharField(max_length = 100)
    slug = models.SlugField()
    # Slug mostly use for a tags / for example when we click on a link it will check slug and go for it
    main_text = models.TextField()
    date = models.DateTimeField(auto_now_add = True)
    image = models.ImageField(default='default.jpg', blank=True)
    # Foreingkey Used for save the author name In Database(who publish the article)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)


# We add this function to change Article Objects name into real name.
# use title as Article Name
    def __str__(self):
        return self.title


# This method used to only show first 50 characters of a article
    def snippet(self):
        return self.main_text[:50] + ' ...'

articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Articles
        fields = ['title', 'slug', 'main_text', 'image']

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.

# Here we say, if the method was POST, get info from user and if that info is valid, save them in DB
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)

            return redirect('articles:list')




# Else --> ( if method was get ) show a empty list to user
    else:
        form = UserCreationForm()

    return render(request, 'accounts/signup.html', {'form':form})



# Function to login
def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
            # if it was valid -->
            user = form.get_user()
            login(request, user)

            # here we mean if there is a 'next' in our request.POST: do this:
            if 'next' in request.POST:
                return redirect(request.POST.get('next')) # This 'next' is the name of input value in login.html 

            else:
                return redirect('articles:list')


    else:
        form = AuthenticationForm()

    return render(request, 'accounts/login.html', {'form':form})




# Logout Function
def logout_view(request):
    if request.method == 'POST':
        logout(request)

        return redirect('articles:list')

articles/views.py
from django.shortcuts import render, HttpResponse, redirect
from . import models
from django.contrib.auth.decorators import login_required
from . import forms

# Create your views here.

def articles_list(request):
    # it means save all Article(articles all are object) and save them here
    articles = models.Articles.objects.all().order_by('-date') # This date is our date in models.py

    # we have to use path for render --> articles folder and articles_list.html File
    # The third arguement is a dict that let us use our articles in our template(html file)
    return render(request, 'articles/articleslist.html', {'articles':articles})


# This slug arguement is come from urls.py(articles)
def article_detail(request, slug):
    # return HttpResponse(slug)
    article = models.Articles.objects.get(slug=slug) # first slug is arguement of func and second is models.py slug

    # we will send and render these articles that we get above and send them to article_detail.html
    return render(request, 'articles/article_detail.html', {'article':article})



# it's a decorator in python and django
@login_required(login_url = '/accounts/login')
def create_article(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid:
            instance = form.save(commit = False) # Don't save this form in Database
            instance.author = request.user # Find the user from login of him/her
            instance.save() # Now save the form with user name
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request, 'articles/create_articles.html', {'form':form})

djangoBlog/views.py
# we import 2 module here
from django.shortcuts import render
# http respose module will catch http requests and print sth in that URL
# if that url is called
from django.shortcuts import HttpResponse


# This request is just for django and it not like python
def about(request):
    # return HttpResponse('Hi there!')
    return render(request, 'about.html')
    # render will Rend to request the Special Page that we introduce
    # render will take 2 parameters/ first is request same as function
    # second is our file that we want to connect with urls :) here is home.html



# This is our Home and root page :)
def home(request):
    # return HttpResponse('This is our Home :)')
    return render(request, 'home.html')

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
<h1>Login</h1>

<!-- in form tag -> url 'accounts:login' -> account is the name of app_name variable in urls.py and login is the path and url pattern-->
<form class="site-form" action="{% url 'accounts:login' %}" method="post">
  {{form}}
  {% csrf_token %}


<!-- if request.GET.next == True:-->
  {% if request.GET.next %}
  <input type="hidden" name="next" value="{{request.GET.next}}"> <!-- type='hiddden'  because we dont wanna show sth to users -->

  {% endif %}


  <input type="submit" name="" value="login">
</form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block content %}
<h1>Sign Up</h1>
<form class="site-form" action="{% url 'accounts:signup' %}" method="post">
  {{form}}
  {% csrf_token %}
  <input type="submit" name="" value="signup">
</form>
{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="article-detail">
  <div class="article">
    <img src="{{article.image.url}}" alt="">
    <h1>{{article.title}}</h1>
    <p>{{article.main_text}}</p>
    <p>{{article.date}}</p>


  </div>

</div>
{% endblock %}

articles/templates/articles/articleslist.html
{% extends 'base.html' %}
<!-- it means load and extends base.html file here-->

  <!-- these called template mehtods -->
    <!-- curly braces and double % use when we want to use a pythonic (if-while-for etc..) -->
    <!-- double Curly braces use when we want to call a data from someWhere -->

    <!-- This articles refer to views.py 'Article' Variable that rend in rencer Function and with article key pair to article value
    when we render it in views.py we can now read our data here
    when we use a pythonic code we have to make it finish some where like this bellow: -->

{% block title %}
Articles List
{% endblock %}
<!-- here we say, use the codes betweem two block for base.html-->

    {% block content %}


    <h1>Articles List</h1>


 <div class="articles">


    {% for article in articles %}

  <div class="article">


      <h2>
      <!-- here  we use slug= article.slug and get slug from article in models.py -->
      <a href="{% url 'articles:detail' slug=article.slug %}">{{article.title}}</a>   <!-- we create link with article.title :) -->
      </h2>

      <p>{{article.snippet}}</p>  <!-- Read article.main_text from our models.py -->
      <p>{{article.date}}</p>       <!-- Read article.date from our models.py -->

      <p class="author">Added by {{article.author.username}}</p>

</div>
    {% endfor %}
    
</div>


    {% endblock %}

articles/templates/articles/create_articles.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

  <div class="create-article">
    <h1>
      Create Your Article!
    </h1>
    <form class="site-form" action="{% url 'articles:create' %}" method="post", enctype="multipart/form-data"> <!-- we use enctype for send photo to the server and upload photoes-->
        {{form}}
        {% csrf_token %}
        <input type="submit" name="" value="Create">
    </form>
  </div>

<script src="{% static 'slugify.js' %}"></script>

{% endblock %}

templates/about.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>About</title>
  </head>
  <body>
    <h1>About us</h1>
    <p></p>
  </body>
</html>

templates/base.html
{% load static %}

<!-- This is the Base.html that use for create a base html that used for all others html file -->
<!-- when ever we want to use as a instance, we use "curly bracket and Percent sign + block <name>"" and then "endblock" -->
<!-- That part is gonna use as a Variable I guess ! and can change in each html file -->


<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">

    <title>
    {% block title %}

    {% endblock %}
    </title>

    <link rel="stylesheet" href='{% static "style.css" %}'>

  </head>
  <body>



<header>
  <h2><a href="{% url 'articles:list' %}">LOGO</a></h2>

  <!-- articles: list  -> article refer to app name and list is the name in that app name -->

  <nav>
    <ul>
      {% if user.is_authenticated %} <!--  If user is login in account -->
      <li>
        <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
          {% csrf_token %}
          <button type="submit">Logout</button>

        </form>
      </li>

  <li>
    <a  class="highlight" href="{% url 'articles:create' %}">Create New Article</a>
  </li>

      {% else %} <!-- If user not login in her/his account -->
      <li>
        <a href="{% url 'accounts:login' %}">Login</a>
      </li>

      <li>
      <a href="{% url 'accounts:signup' %}">Signup</a>
    </li>


      {% endif %}
    </ul>
  </nav>
</header>



<div class="wrapper">
  {% block content %}
  {% endblock %}
</div>

  </body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Home</title>
  </head>
  <body>
    <h1>Home</h1>
    <p>Welcome to my Blog !</p>
  </body>
</html>